---
--- Generated by Table Tools
--- Created by user.
--- DateTime: 2019/11/20 10:11
---

require('type')

BeHit_headers = {
		"presentid",  
		"hitid",
		"hit_front",
		"hit_front_curve",
		"hit_back",   
		"hit_back_curve",
		"hit_left",
		"hit_left_curve",
		"hit_right",  
		"hit_right_curve",
		"death",
		"death_curve",
		"cameraShake", 
		"qte",
		"QTETime",
		"setFace",
		"postEffect",
		"postEffectParams",
		"BuffIDs",
		"BuffTime",
		"PVESP",
		"PVPSP",
		"PostEffectTime",
		"ChangeFlyTime",
		"setHitFromDir"  }

BeHit_types = {
		UINT32,  
		INT32,  -- hitid
		STRING_ARR, -- hit_front
		STRING_ARR, -- hit_front_curve
		STRING_ARR,
		STRING_ARR,
		STRING_ARR,
		STRING_ARR, -- hit_left_curve
		STRING_ARR,
		STRING_ARR, -- hit_right_curve
		STRING,  -- death
		STRING_ARR, -- death_curve
		FLOAT_ARR,
		UINT32_ARR, -- qte
		FLOAT_LIST,
		INT32,
		INT32,
		FLOAT_ARR, -- postEffectParams
		INT32_LIST,
		FLOAT_LIST,
		INT32,
		INT32, --PVPSP
		FLOAT_SEQ,
		FLOAT_SEQ, -- ChangeFlyTime
		BOOLEAN }

ActorTable_headers = {
		"actorId",
		"rotation",
		"scale",
		"offset",
		"idle",
		"touch",
		"interact1",
		"interact2",
		"interact3",
		"filters",
		"pvpStartAction" }

ActorTable_types = {
		UINT32,
		FLOAT_SEQ,
		FLOAT_SEQ,
		FLOAT_SEQ,
		STRING,
		STRING,
		STRING,
		STRING,
		STRING,
		UINT32_ARR,
		STRING_ARR }

Tables = {
	"ActorTable",
	"BeHit"
}
