---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by user.
--- DateTime: 2019/11/20 10:11
---

--
-- 表格里所有用到的数据类型定义
--


 -- basic
INT32     = 1 
UINT32    = 2
UINT16    = 3
INT64     = 4
FLOAT     = 5
DOUBLE    = 6
BOOLEAN   = 7
STRING    = 8


-- array
INT32_ARR    = 10 
UINT32_ARR   = 11
FLOAT_ARR    = 12
DOUBLE_ARR   = 13
STRING_ARR   = 14


-- seqRef
INT32_SEQ     = 20 
UINT32_SEQ    = 21
FLOAT_SEQ     = 22
DOUBLE_SEQ    = 23
STRING_SEQ    = 24


-- seqlist
INT32_LIST     = 30 
UINT32_LIST    = 31
FLOAT_LIST     = 32
DOUBLE_LIST    = 33
STRING_LIST    = 34