---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by user.
--- DateTime: 2019/11/12 10:11
---

util = {}

function util.table_len(t)
    --当我们获取 table 的长度的时候 #table会把nil计算进去, 而此方法不会计入nil
    local len = 0
    for k, v in pairs(t) do
        len = len + 1
    end
    return len
end


function util.getn(t)
    --lua5.0以上版本去除了table.getn方法
    return #t
end

function util.table_maxn(t)
    -- table.maxn 在 Lua5.2 之后该方法已经不存在了，我们定义了 table_maxn 方法来实现
    -- tbl = { [1] = 2, [2] = 6, [3] = 34, [26] = 5 }
    -- print("tbl 最大值：", table_maxn(tbl), "tbl 长度 ", #tbl)
    local mn = nil;
    for k, v in pairs(t) do
        if (mn == nil) then
            mn = v
        end
        if mn < v then
            mn = v
        end
    end
    return mn
end

return util